sonar.projectKey=kshishtovsky_aqueduct
sonar.organization=kshishtovsky
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage_clean.out
sonar.go.golangci-lint.reportPaths=golangci-lint-report.out

sonar.sourceEncoding=UTF-8
